version: '2'
services:

  dbserver:
    image: mysql
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
    environment:
            MYSQL_DATABASE: blog_db
            MYSQL_USER: sboot
            MYSQL_PASSWORD: sboot
            MYSQL_ROOT_PASSWORD: root

  myadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - dbserver
    environment:
      PMA_ARBITRARY: 1
      PMA_HOST: dbserver
      PMA_USER: root
      PMA_PASSWORD: root
    ports:
      - "1111:80"
