version: '3'
services:
  myservice:
    build: .
    container_name: myservice
    command: tail -f /dev/null
    volumes:
      - .:/work
      - my-vol:/data
    links:
      - myweb
      - mydb
  myweb:
    image: nginx
    container_name: myweb
    restart: always
    volumes:
      - my-vol:/data
    ports:
      - 20080:80
  mydb:
    image: mysql
    container_name: mydb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - my-vol:/data
    ports:
      - 23306:3306
volumes:
  my-vol:
