version: '2'
services:
  app-tomcat:
    environment:
      - "TZ=Japan"
    build: ./tomcat
    volumes:
      - ./tomcat/apps/:/usr/local/tomcat/webapps
    ports:
      - "8081:8080"
    links:
      - app-mysql

  app-mysql:
    build: ./mysql/
    volumes:
      - ./mysql/mysql_data:/var/lib/mysql
      - ./mysql/sqls:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
    environment:
            - "TZ=Japan"
            - MYSQL_DATABASE=blog_db
            - MYSQL_USER=sboot
            - MYSQL_PASSWORD=sboot
            - MYSQL_ROOT_PASSWORD=root
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mysql
      - PMA_USER=root
      - PMA_PASSWORD=root
    links:
      - app-mysql
    ports:
      - 1111:80
    volumes:
      - /session
